# Generated by Django 4.2.2 on 2024-05-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='idcard',
        ),
    ]
