# Generated by Django 4.2.2 on 2024-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_email_users_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_possess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(default='null', max_length=255)),
                ('Aircon_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Users_possess',
            },
        ),
    ]
