# Generated by Django 4.2.2 on 2024-06-18 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_possess'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_possess',
            name='opentime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
