# Generated by Django 4.2.2 on 2024-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aircon_name', models.CharField(max_length=255)),
                ('CreadedTime', models.DateTimeField(auto_now_add=True)),
                ('Aircon_setting_model', models.CharField(default='0', max_length=5)),
                ('Aircon_setting_temp', models.CharField(default='25', max_length=5)),
                ('Aircon_setting_wind', models.CharField(default='2', max_length=5)),
                ('Aircon_current_model', models.CharField(default='0', max_length=5)),
                ('Aircon_current_wind', models.CharField(default='2', max_length=5)),
                ('room_current_temp', models.CharField(default='30', max_length=5)),
                ('room_img', models.CharField(default='img/groupimg/default.png', max_length=255)),
                ('pre_setting_date', models.DateTimeField(auto_now_add=True)),
                ('wait_time', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('is_serviced', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Aircon_info',
            },
        ),
    ]
