# Generated by Django 4.2.2 on 2024-06-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Aircon_setting_temp',
            field=models.FloatField(default=25.0, max_length=5),
        ),
    ]
