# Generated by Django 4.2.2 on 2024-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='room_current_temp',
            field=models.CharField(default='30', max_length=5),
        ),
    ]
