# Generated by Django 4.2.2 on 2024-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircons', '0002_alter_group_aircon_setting_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='room_current_temp',
            field=models.FloatField(default=25.0, max_length=5),
        ),
    ]
