# Generated by Django 4.2.2 on 2024-06-18 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aircons', '0002_alter_group_room_current_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pre_setting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
