# Generated by Django 4.2.2 on 2024-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircons', '0003_alter_group_room_current_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Aircon_current_wind',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
